export const LOADING_EVENT = 'USER_LOADING'
export const LOADING_HEDDIN = 'LOADING_HEDDIN'
export const USER_SUCCESS  = 'USER_SUCCESS'
export const USER_ERROR_ARR   = 'USER_ERROR_ARR'
export const USER_ERROR    = 'USER_ERROR'
export const USER_LOGOUT   = 'USER_LOGOUT'

export const USER_SUCCESS_LOGIN = 'USER_SUCCESS_LOGIN'

export const USER_BECOME_EMPTY = 'USER_BECOME_EMPTY'

export const IMAGE_RANDOM_PUP = 'IMAGE_RANDOM_PUP'

export const PUT_IN_USER_REGISTER = 'PUT_IN_USER_REGISTER'

export const DELETE_ERRORS = 'DELETE_ERRORS'

export const GET_SINGLE_USER = 'GET_SINGLE_USER'

export const CHANGE_DATA_USER = 'CHANGE_DATA_USER'
